#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KZONE.UI
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="KZONE_HKC_KWF22003L_4L_5R_HIS")]
	public partial class DBHISSETDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertSBCS_CIMMESSAGEHISTORY(SBCS_CIMMESSAGEHISTORY instance);
    partial void UpdateSBCS_CIMMESSAGEHISTORY(SBCS_CIMMESSAGEHISTORY instance);
    partial void DeleteSBCS_CIMMESSAGEHISTORY(SBCS_CIMMESSAGEHISTORY instance);
    partial void InsertSBCS_PROCESSDATAHISTORY(SBCS_PROCESSDATAHISTORY instance);
    partial void UpdateSBCS_PROCESSDATAHISTORY(SBCS_PROCESSDATAHISTORY instance);
    partial void DeleteSBCS_PROCESSDATAHISTORY(SBCS_PROCESSDATAHISTORY instance);
    partial void InsertSBCS_UNITHISTORY(SBCS_UNITHISTORY instance);
    partial void UpdateSBCS_UNITHISTORY(SBCS_UNITHISTORY instance);
    partial void DeleteSBCS_UNITHISTORY(SBCS_UNITHISTORY instance);
    partial void InsertSBCS_ALARMHISTORY(SBCS_ALARMHISTORY instance);
    partial void UpdateSBCS_ALARMHISTORY(SBCS_ALARMHISTORY instance);
    partial void DeleteSBCS_ALARMHISTORY(SBCS_ALARMHISTORY instance);
    partial void InsertSBCS_NODEHISTORY(SBCS_NODEHISTORY instance);
    partial void UpdateSBCS_NODEHISTORY(SBCS_NODEHISTORY instance);
    partial void DeleteSBCS_NODEHISTORY(SBCS_NODEHISTORY instance);
    partial void InsertSBCS_TANKHISTORY(SBCS_TANKHISTORY instance);
    partial void UpdateSBCS_TANKHISTORY(SBCS_TANKHISTORY instance);
    partial void DeleteSBCS_TANKHISTORY(SBCS_TANKHISTORY instance);
    partial void InsertSBCS_RECIPEHISTORY(SBCS_RECIPEHISTORY instance);
    partial void UpdateSBCS_RECIPEHISTORY(SBCS_RECIPEHISTORY instance);
    partial void DeleteSBCS_RECIPEHISTORY(SBCS_RECIPEHISTORY instance);
    partial void InsertSBCS_JOBHISTORY(SBCS_JOBHISTORY instance);
    partial void UpdateSBCS_JOBHISTORY(SBCS_JOBHISTORY instance);
    partial void DeleteSBCS_JOBHISTORY(SBCS_JOBHISTORY instance);
    #endregion
		
		public DBHISSETDataContext() : 
				base(global::KZONE.UI.Properties.Settings.Default.UniBCS_HKC_HISConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBHISSETDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBHISSETDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBHISSETDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBHISSETDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<SBCS_CIMMESSAGEHISTORY> SBCS_CIMMESSAGEHISTORY
		{
			get
			{
				return this.GetTable<SBCS_CIMMESSAGEHISTORY>();
			}
		}
		
		public System.Data.Linq.Table<SBCS_PROCESSDATAHISTORY> SBCS_PROCESSDATAHISTORY
		{
			get
			{
				return this.GetTable<SBCS_PROCESSDATAHISTORY>();
			}
		}
		
		public System.Data.Linq.Table<SBCS_UNITHISTORY> SBCS_UNITHISTORY
		{
			get
			{
				return this.GetTable<SBCS_UNITHISTORY>();
			}
		}
		
		public System.Data.Linq.Table<SBCS_ALARMHISTORY> SBCS_ALARMHISTORY
		{
			get
			{
				return this.GetTable<SBCS_ALARMHISTORY>();
			}
		}
		
		public System.Data.Linq.Table<SBCS_NODEHISTORY> SBCS_NODEHISTORY
		{
			get
			{
				return this.GetTable<SBCS_NODEHISTORY>();
			}
		}
		
		public System.Data.Linq.Table<SBCS_TANKHISTORY> SBCS_TANKHISTORY
		{
			get
			{
				return this.GetTable<SBCS_TANKHISTORY>();
			}
		}
		
		public System.Data.Linq.Table<SBCS_RECIPEHISTORY> SBCS_RECIPEHISTORY
		{
			get
			{
				return this.GetTable<SBCS_RECIPEHISTORY>();
			}
		}
		
		public System.Data.Linq.Table<SBCS_TACTDATAHISTORY> SBCS_TACTDATAHISTORY
		{
			get
			{
				return this.GetTable<SBCS_TACTDATAHISTORY>();
			}
		}
		
		public System.Data.Linq.Table<SBCS_JOBHISTORY> SBCS_JOBHISTORY
		{
			get
			{
				return this.GetTable<SBCS_JOBHISTORY>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SBCS_CIMMESSAGEHISTORY")]
	public partial class SBCS_CIMMESSAGEHISTORY : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _OBJECTKEY;
		
		private System.DateTime _UPDATETIME;
		
		private string _NODEID;
		
		private string _NODENO;
		
		private string _MESSAGEID;
		
		private string _MESSAGETEXT;
		
		private string _MESSAGESTATUS;
		
		private string _OPERATORID;
		
		private string _REMARK;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnOBJECTKEYChanging(long value);
    partial void OnOBJECTKEYChanged();
    partial void OnUPDATETIMEChanging(System.DateTime value);
    partial void OnUPDATETIMEChanged();
    partial void OnNODEIDChanging(string value);
    partial void OnNODEIDChanged();
    partial void OnNODENOChanging(string value);
    partial void OnNODENOChanged();
    partial void OnMESSAGEIDChanging(string value);
    partial void OnMESSAGEIDChanged();
    partial void OnMESSAGETEXTChanging(string value);
    partial void OnMESSAGETEXTChanged();
    partial void OnMESSAGESTATUSChanging(string value);
    partial void OnMESSAGESTATUSChanged();
    partial void OnOPERATORIDChanging(string value);
    partial void OnOPERATORIDChanged();
    partial void OnREMARKChanging(string value);
    partial void OnREMARKChanged();
    #endregion
		
		public SBCS_CIMMESSAGEHISTORY()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OBJECTKEY", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long OBJECTKEY
		{
			get
			{
				return this._OBJECTKEY;
			}
			set
			{
				if ((this._OBJECTKEY != value))
				{
					this.OnOBJECTKEYChanging(value);
					this.SendPropertyChanging();
					this._OBJECTKEY = value;
					this.SendPropertyChanged("OBJECTKEY");
					this.OnOBJECTKEYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPDATETIME", DbType="DateTime NOT NULL")]
		public System.DateTime UPDATETIME
		{
			get
			{
				return this._UPDATETIME;
			}
			set
			{
				if ((this._UPDATETIME != value))
				{
					this.OnUPDATETIMEChanging(value);
					this.SendPropertyChanging();
					this._UPDATETIME = value;
					this.SendPropertyChanged("UPDATETIME");
					this.OnUPDATETIMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NODEID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string NODEID
		{
			get
			{
				return this._NODEID;
			}
			set
			{
				if ((this._NODEID != value))
				{
					this.OnNODEIDChanging(value);
					this.SendPropertyChanging();
					this._NODEID = value;
					this.SendPropertyChanged("NODEID");
					this.OnNODEIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NODENO", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string NODENO
		{
			get
			{
				return this._NODENO;
			}
			set
			{
				if ((this._NODENO != value))
				{
					this.OnNODENOChanging(value);
					this.SendPropertyChanging();
					this._NODENO = value;
					this.SendPropertyChanged("NODENO");
					this.OnNODENOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MESSAGEID", DbType="VarChar(10)")]
		public string MESSAGEID
		{
			get
			{
				return this._MESSAGEID;
			}
			set
			{
				if ((this._MESSAGEID != value))
				{
					this.OnMESSAGEIDChanging(value);
					this.SendPropertyChanging();
					this._MESSAGEID = value;
					this.SendPropertyChanged("MESSAGEID");
					this.OnMESSAGEIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MESSAGETEXT", DbType="VarChar(80) NOT NULL", CanBeNull=false)]
		public string MESSAGETEXT
		{
			get
			{
				return this._MESSAGETEXT;
			}
			set
			{
				if ((this._MESSAGETEXT != value))
				{
					this.OnMESSAGETEXTChanging(value);
					this.SendPropertyChanging();
					this._MESSAGETEXT = value;
					this.SendPropertyChanged("MESSAGETEXT");
					this.OnMESSAGETEXTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MESSAGESTATUS", DbType="VarChar(15)")]
		public string MESSAGESTATUS
		{
			get
			{
				return this._MESSAGESTATUS;
			}
			set
			{
				if ((this._MESSAGESTATUS != value))
				{
					this.OnMESSAGESTATUSChanging(value);
					this.SendPropertyChanging();
					this._MESSAGESTATUS = value;
					this.SendPropertyChanged("MESSAGESTATUS");
					this.OnMESSAGESTATUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OPERATORID", DbType="VarChar(50)")]
		public string OPERATORID
		{
			get
			{
				return this._OPERATORID;
			}
			set
			{
				if ((this._OPERATORID != value))
				{
					this.OnOPERATORIDChanging(value);
					this.SendPropertyChanging();
					this._OPERATORID = value;
					this.SendPropertyChanged("OPERATORID");
					this.OnOPERATORIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REMARK", DbType="VarChar(50)")]
		public string REMARK
		{
			get
			{
				return this._REMARK;
			}
			set
			{
				if ((this._REMARK != value))
				{
					this.OnREMARKChanging(value);
					this.SendPropertyChanging();
					this._REMARK = value;
					this.SendPropertyChanged("REMARK");
					this.OnREMARKChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SBCS_PROCESSDATAHISTORY")]
	public partial class SBCS_PROCESSDATAHISTORY : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _OBJECTKEY;
		
		private System.Nullable<int> _CASSETTESEQNO;
		
		private System.Nullable<int> _CASSETTESLOTNO;
		
		private string _JOBID;
		
		private string _TRXID;
		
		private string _MESCONTROLSTATE;
		
		private string _NODEID;
		
		private System.Nullable<System.DateTime> _UPDATETIME;
		
		private string _FILENAMA;
		
		private string _LOCALPROCESSSTARTTIME;
		
		private string _LOCALPROCSSSENDTIME;
		
		private System.Nullable<int> _PROCESSTIME;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnOBJECTKEYChanging(long value);
    partial void OnOBJECTKEYChanged();
    partial void OnCASSETTESEQNOChanging(System.Nullable<int> value);
    partial void OnCASSETTESEQNOChanged();
    partial void OnCASSETTESLOTNOChanging(System.Nullable<int> value);
    partial void OnCASSETTESLOTNOChanged();
    partial void OnJOBIDChanging(string value);
    partial void OnJOBIDChanged();
    partial void OnTRXIDChanging(string value);
    partial void OnTRXIDChanged();
    partial void OnMESCONTROLSTATEChanging(string value);
    partial void OnMESCONTROLSTATEChanged();
    partial void OnNODEIDChanging(string value);
    partial void OnNODEIDChanged();
    partial void OnUPDATETIMEChanging(System.Nullable<System.DateTime> value);
    partial void OnUPDATETIMEChanged();
    partial void OnFILENAMAChanging(string value);
    partial void OnFILENAMAChanged();
    partial void OnLOCALPROCESSSTARTTIMEChanging(string value);
    partial void OnLOCALPROCESSSTARTTIMEChanged();
    partial void OnLOCALPROCSSSENDTIMEChanging(string value);
    partial void OnLOCALPROCSSSENDTIMEChanged();
    partial void OnPROCESSTIMEChanging(System.Nullable<int> value);
    partial void OnPROCESSTIMEChanged();
    #endregion
		
		public SBCS_PROCESSDATAHISTORY()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OBJECTKEY", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long OBJECTKEY
		{
			get
			{
				return this._OBJECTKEY;
			}
			set
			{
				if ((this._OBJECTKEY != value))
				{
					this.OnOBJECTKEYChanging(value);
					this.SendPropertyChanging();
					this._OBJECTKEY = value;
					this.SendPropertyChanged("OBJECTKEY");
					this.OnOBJECTKEYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CASSETTESEQNO", DbType="Int")]
		public System.Nullable<int> CASSETTESEQNO
		{
			get
			{
				return this._CASSETTESEQNO;
			}
			set
			{
				if ((this._CASSETTESEQNO != value))
				{
					this.OnCASSETTESEQNOChanging(value);
					this.SendPropertyChanging();
					this._CASSETTESEQNO = value;
					this.SendPropertyChanged("CASSETTESEQNO");
					this.OnCASSETTESEQNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CASSETTESLOTNO", DbType="Int")]
		public System.Nullable<int> CASSETTESLOTNO
		{
			get
			{
				return this._CASSETTESLOTNO;
			}
			set
			{
				if ((this._CASSETTESLOTNO != value))
				{
					this.OnCASSETTESLOTNOChanging(value);
					this.SendPropertyChanging();
					this._CASSETTESLOTNO = value;
					this.SendPropertyChanged("CASSETTESLOTNO");
					this.OnCASSETTESLOTNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JOBID", DbType="VarChar(50)")]
		public string JOBID
		{
			get
			{
				return this._JOBID;
			}
			set
			{
				if ((this._JOBID != value))
				{
					this.OnJOBIDChanging(value);
					this.SendPropertyChanging();
					this._JOBID = value;
					this.SendPropertyChanged("JOBID");
					this.OnJOBIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRXID", DbType="VarChar(50)")]
		public string TRXID
		{
			get
			{
				return this._TRXID;
			}
			set
			{
				if ((this._TRXID != value))
				{
					this.OnTRXIDChanging(value);
					this.SendPropertyChanging();
					this._TRXID = value;
					this.SendPropertyChanged("TRXID");
					this.OnTRXIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MESCONTROLSTATE", DbType="VarChar(50)")]
		public string MESCONTROLSTATE
		{
			get
			{
				return this._MESCONTROLSTATE;
			}
			set
			{
				if ((this._MESCONTROLSTATE != value))
				{
					this.OnMESCONTROLSTATEChanging(value);
					this.SendPropertyChanging();
					this._MESCONTROLSTATE = value;
					this.SendPropertyChanged("MESCONTROLSTATE");
					this.OnMESCONTROLSTATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NODEID", DbType="VarChar(50)")]
		public string NODEID
		{
			get
			{
				return this._NODEID;
			}
			set
			{
				if ((this._NODEID != value))
				{
					this.OnNODEIDChanging(value);
					this.SendPropertyChanging();
					this._NODEID = value;
					this.SendPropertyChanged("NODEID");
					this.OnNODEIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPDATETIME", DbType="DateTime")]
		public System.Nullable<System.DateTime> UPDATETIME
		{
			get
			{
				return this._UPDATETIME;
			}
			set
			{
				if ((this._UPDATETIME != value))
				{
					this.OnUPDATETIMEChanging(value);
					this.SendPropertyChanging();
					this._UPDATETIME = value;
					this.SendPropertyChanged("UPDATETIME");
					this.OnUPDATETIMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FILENAMA", DbType="VarChar(100)")]
		public string FILENAMA
		{
			get
			{
				return this._FILENAMA;
			}
			set
			{
				if ((this._FILENAMA != value))
				{
					this.OnFILENAMAChanging(value);
					this.SendPropertyChanging();
					this._FILENAMA = value;
					this.SendPropertyChanged("FILENAMA");
					this.OnFILENAMAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOCALPROCESSSTARTTIME", DbType="VarChar(50)")]
		public string LOCALPROCESSSTARTTIME
		{
			get
			{
				return this._LOCALPROCESSSTARTTIME;
			}
			set
			{
				if ((this._LOCALPROCESSSTARTTIME != value))
				{
					this.OnLOCALPROCESSSTARTTIMEChanging(value);
					this.SendPropertyChanging();
					this._LOCALPROCESSSTARTTIME = value;
					this.SendPropertyChanged("LOCALPROCESSSTARTTIME");
					this.OnLOCALPROCESSSTARTTIMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOCALPROCSSSENDTIME", DbType="VarChar(50)")]
		public string LOCALPROCSSSENDTIME
		{
			get
			{
				return this._LOCALPROCSSSENDTIME;
			}
			set
			{
				if ((this._LOCALPROCSSSENDTIME != value))
				{
					this.OnLOCALPROCSSSENDTIMEChanging(value);
					this.SendPropertyChanging();
					this._LOCALPROCSSSENDTIME = value;
					this.SendPropertyChanged("LOCALPROCSSSENDTIME");
					this.OnLOCALPROCSSSENDTIMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROCESSTIME", DbType="Int")]
		public System.Nullable<int> PROCESSTIME
		{
			get
			{
				return this._PROCESSTIME;
			}
			set
			{
				if ((this._PROCESSTIME != value))
				{
					this.OnPROCESSTIMEChanging(value);
					this.SendPropertyChanging();
					this._PROCESSTIME = value;
					this.SendPropertyChanged("PROCESSTIME");
					this.OnPROCESSTIMEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SBCS_UNITHISTORY")]
	public partial class SBCS_UNITHISTORY : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _OBJECTKEY;
		
		private System.DateTime _UPDATETIME;
		
		private string _NODEID;
		
		private string _NODENO;
		
		private System.Nullable<int> _UNITNO;
		
		private string _UNITID;
		
		private string _UNITSTATUS;
		
		private string _UNITTYPE;
		
		private string _UNITRECIPEID;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnOBJECTKEYChanging(long value);
    partial void OnOBJECTKEYChanged();
    partial void OnUPDATETIMEChanging(System.DateTime value);
    partial void OnUPDATETIMEChanged();
    partial void OnNODEIDChanging(string value);
    partial void OnNODEIDChanged();
    partial void OnNODENOChanging(string value);
    partial void OnNODENOChanged();
    partial void OnUNITNOChanging(System.Nullable<int> value);
    partial void OnUNITNOChanged();
    partial void OnUNITIDChanging(string value);
    partial void OnUNITIDChanged();
    partial void OnUNITSTATUSChanging(string value);
    partial void OnUNITSTATUSChanged();
    partial void OnUNITTYPEChanging(string value);
    partial void OnUNITTYPEChanged();
    partial void OnUNITRECIPEIDChanging(string value);
    partial void OnUNITRECIPEIDChanged();
    #endregion
		
		public SBCS_UNITHISTORY()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OBJECTKEY", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long OBJECTKEY
		{
			get
			{
				return this._OBJECTKEY;
			}
			set
			{
				if ((this._OBJECTKEY != value))
				{
					this.OnOBJECTKEYChanging(value);
					this.SendPropertyChanging();
					this._OBJECTKEY = value;
					this.SendPropertyChanged("OBJECTKEY");
					this.OnOBJECTKEYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPDATETIME", DbType="DateTime NOT NULL")]
		public System.DateTime UPDATETIME
		{
			get
			{
				return this._UPDATETIME;
			}
			set
			{
				if ((this._UPDATETIME != value))
				{
					this.OnUPDATETIMEChanging(value);
					this.SendPropertyChanging();
					this._UPDATETIME = value;
					this.SendPropertyChanged("UPDATETIME");
					this.OnUPDATETIMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NODEID", DbType="VarChar(50)")]
		public string NODEID
		{
			get
			{
				return this._NODEID;
			}
			set
			{
				if ((this._NODEID != value))
				{
					this.OnNODEIDChanging(value);
					this.SendPropertyChanging();
					this._NODEID = value;
					this.SendPropertyChanged("NODEID");
					this.OnNODEIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NODENO", DbType="VarChar(50)")]
		public string NODENO
		{
			get
			{
				return this._NODENO;
			}
			set
			{
				if ((this._NODENO != value))
				{
					this.OnNODENOChanging(value);
					this.SendPropertyChanging();
					this._NODENO = value;
					this.SendPropertyChanged("NODENO");
					this.OnNODENOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UNITNO", DbType="Int")]
		public System.Nullable<int> UNITNO
		{
			get
			{
				return this._UNITNO;
			}
			set
			{
				if ((this._UNITNO != value))
				{
					this.OnUNITNOChanging(value);
					this.SendPropertyChanging();
					this._UNITNO = value;
					this.SendPropertyChanged("UNITNO");
					this.OnUNITNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UNITID", DbType="VarChar(50)")]
		public string UNITID
		{
			get
			{
				return this._UNITID;
			}
			set
			{
				if ((this._UNITID != value))
				{
					this.OnUNITIDChanging(value);
					this.SendPropertyChanging();
					this._UNITID = value;
					this.SendPropertyChanged("UNITID");
					this.OnUNITIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UNITSTATUS", DbType="VarChar(50)")]
		public string UNITSTATUS
		{
			get
			{
				return this._UNITSTATUS;
			}
			set
			{
				if ((this._UNITSTATUS != value))
				{
					this.OnUNITSTATUSChanging(value);
					this.SendPropertyChanging();
					this._UNITSTATUS = value;
					this.SendPropertyChanged("UNITSTATUS");
					this.OnUNITSTATUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UNITTYPE", DbType="VarChar(50)")]
		public string UNITTYPE
		{
			get
			{
				return this._UNITTYPE;
			}
			set
			{
				if ((this._UNITTYPE != value))
				{
					this.OnUNITTYPEChanging(value);
					this.SendPropertyChanging();
					this._UNITTYPE = value;
					this.SendPropertyChanged("UNITTYPE");
					this.OnUNITTYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UNITRECIPEID", DbType="VarChar(50)")]
		public string UNITRECIPEID
		{
			get
			{
				return this._UNITRECIPEID;
			}
			set
			{
				if ((this._UNITRECIPEID != value))
				{
					this.OnUNITRECIPEIDChanging(value);
					this.SendPropertyChanging();
					this._UNITRECIPEID = value;
					this.SendPropertyChanged("UNITRECIPEID");
					this.OnUNITRECIPEIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SBCS_ALARMHISTORY")]
	public partial class SBCS_ALARMHISTORY : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _OBJECTKEY;
		
		private string _EVENTNAME;
		
		private System.Nullable<System.DateTime> _UPDATETIME;
		
		private string _ALARMID;
		
		private string _ALARMADDRESS;
		
		private string _ALARMCODE;
		
		private string _ALARMLEVEL;
		
		private string _ALARMTEXT;
		
		private string _ALARMSTATUS;
		
		private string _NODEID;
		
		private string _ALARMUNIT;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnOBJECTKEYChanging(long value);
    partial void OnOBJECTKEYChanged();
    partial void OnEVENTNAMEChanging(string value);
    partial void OnEVENTNAMEChanged();
    partial void OnUPDATETIMEChanging(System.Nullable<System.DateTime> value);
    partial void OnUPDATETIMEChanged();
    partial void OnALARMIDChanging(string value);
    partial void OnALARMIDChanged();
    partial void OnALARMADDRESSChanging(string value);
    partial void OnALARMADDRESSChanged();
    partial void OnALARMCODEChanging(string value);
    partial void OnALARMCODEChanged();
    partial void OnALARMLEVELChanging(string value);
    partial void OnALARMLEVELChanged();
    partial void OnALARMTEXTChanging(string value);
    partial void OnALARMTEXTChanged();
    partial void OnALARMSTATUSChanging(string value);
    partial void OnALARMSTATUSChanged();
    partial void OnNODEIDChanging(string value);
    partial void OnNODEIDChanged();
    partial void OnALARMUNITChanging(string value);
    partial void OnALARMUNITChanged();
    #endregion
		
		public SBCS_ALARMHISTORY()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OBJECTKEY", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long OBJECTKEY
		{
			get
			{
				return this._OBJECTKEY;
			}
			set
			{
				if ((this._OBJECTKEY != value))
				{
					this.OnOBJECTKEYChanging(value);
					this.SendPropertyChanging();
					this._OBJECTKEY = value;
					this.SendPropertyChanged("OBJECTKEY");
					this.OnOBJECTKEYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EVENTNAME", DbType="VarChar(50)")]
		public string EVENTNAME
		{
			get
			{
				return this._EVENTNAME;
			}
			set
			{
				if ((this._EVENTNAME != value))
				{
					this.OnEVENTNAMEChanging(value);
					this.SendPropertyChanging();
					this._EVENTNAME = value;
					this.SendPropertyChanged("EVENTNAME");
					this.OnEVENTNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPDATETIME", DbType="DateTime")]
		public System.Nullable<System.DateTime> UPDATETIME
		{
			get
			{
				return this._UPDATETIME;
			}
			set
			{
				if ((this._UPDATETIME != value))
				{
					this.OnUPDATETIMEChanging(value);
					this.SendPropertyChanging();
					this._UPDATETIME = value;
					this.SendPropertyChanged("UPDATETIME");
					this.OnUPDATETIMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ALARMID", DbType="VarChar(50)")]
		public string ALARMID
		{
			get
			{
				return this._ALARMID;
			}
			set
			{
				if ((this._ALARMID != value))
				{
					this.OnALARMIDChanging(value);
					this.SendPropertyChanging();
					this._ALARMID = value;
					this.SendPropertyChanged("ALARMID");
					this.OnALARMIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ALARMADDRESS", DbType="VarChar(50)")]
		public string ALARMADDRESS
		{
			get
			{
				return this._ALARMADDRESS;
			}
			set
			{
				if ((this._ALARMADDRESS != value))
				{
					this.OnALARMADDRESSChanging(value);
					this.SendPropertyChanging();
					this._ALARMADDRESS = value;
					this.SendPropertyChanged("ALARMADDRESS");
					this.OnALARMADDRESSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ALARMCODE", DbType="VarChar(50)")]
		public string ALARMCODE
		{
			get
			{
				return this._ALARMCODE;
			}
			set
			{
				if ((this._ALARMCODE != value))
				{
					this.OnALARMCODEChanging(value);
					this.SendPropertyChanging();
					this._ALARMCODE = value;
					this.SendPropertyChanged("ALARMCODE");
					this.OnALARMCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ALARMLEVEL", DbType="VarChar(50)")]
		public string ALARMLEVEL
		{
			get
			{
				return this._ALARMLEVEL;
			}
			set
			{
				if ((this._ALARMLEVEL != value))
				{
					this.OnALARMLEVELChanging(value);
					this.SendPropertyChanging();
					this._ALARMLEVEL = value;
					this.SendPropertyChanged("ALARMLEVEL");
					this.OnALARMLEVELChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ALARMTEXT", DbType="VarChar(255)")]
		public string ALARMTEXT
		{
			get
			{
				return this._ALARMTEXT;
			}
			set
			{
				if ((this._ALARMTEXT != value))
				{
					this.OnALARMTEXTChanging(value);
					this.SendPropertyChanging();
					this._ALARMTEXT = value;
					this.SendPropertyChanged("ALARMTEXT");
					this.OnALARMTEXTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ALARMSTATUS", DbType="VarChar(50)")]
		public string ALARMSTATUS
		{
			get
			{
				return this._ALARMSTATUS;
			}
			set
			{
				if ((this._ALARMSTATUS != value))
				{
					this.OnALARMSTATUSChanging(value);
					this.SendPropertyChanging();
					this._ALARMSTATUS = value;
					this.SendPropertyChanged("ALARMSTATUS");
					this.OnALARMSTATUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NODEID", DbType="VarChar(50)")]
		public string NODEID
		{
			get
			{
				return this._NODEID;
			}
			set
			{
				if ((this._NODEID != value))
				{
					this.OnNODEIDChanging(value);
					this.SendPropertyChanging();
					this._NODEID = value;
					this.SendPropertyChanged("NODEID");
					this.OnNODEIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ALARMUNIT", DbType="VarChar(50)")]
		public string ALARMUNIT
		{
			get
			{
				return this._ALARMUNIT;
			}
			set
			{
				if ((this._ALARMUNIT != value))
				{
					this.OnALARMUNITChanging(value);
					this.SendPropertyChanging();
					this._ALARMUNIT = value;
					this.SendPropertyChanged("ALARMUNIT");
					this.OnALARMUNITChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SBCS_NODEHISTORY")]
	public partial class SBCS_NODEHISTORY : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _OBJECTKEY;
		
		private System.DateTime _UPDATETIME;
		
		private string _LINEID;
		
		private string _NODEID;
		
		private string _NODENO;
		
		private string _CIMMODE;
		
		private string _CURRENTRECIPEID;
		
		private string _CURRENTSTATUS;
		
		private string _AUTOMANUEL;
		
		private string _UPINLINEMODE;
		
		private string _DOWNINLINEMODE;
		
		private System.Nullable<int> _TFTJOBCOUNT;
		
		private System.Nullable<int> _HFJOBCOUNT;
		
		private System.Nullable<int> _DUMMYJOBCOUNT;
		
		private System.Nullable<int> _UVMASKCOUNT;
		
		private System.Nullable<int> _MQCJOBCOUNT;
		
		private System.Nullable<int> _PRODUCTTYPE;
		
		private string _RECIPECHECK;
		
		private string _GLASSCHECKMODE;
		
		private string _RECIPEAUTOCHANGE;
		
		private string _PRODUCTTYPECHECKMODE;
		
		private string _GROUPINDEXCHECKMODE;
		
		private string _PRODUCTIDCHECKMODE;
		
		private string _DUPLICATECHECKMODE;
		
		private string _ADDLIQUID;
		
		private string _MINLIQUID;
		
		private string _VCRENBLE;
		
		private string _VCRID;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnOBJECTKEYChanging(long value);
    partial void OnOBJECTKEYChanged();
    partial void OnUPDATETIMEChanging(System.DateTime value);
    partial void OnUPDATETIMEChanged();
    partial void OnLINEIDChanging(string value);
    partial void OnLINEIDChanged();
    partial void OnNODEIDChanging(string value);
    partial void OnNODEIDChanged();
    partial void OnNODENOChanging(string value);
    partial void OnNODENOChanged();
    partial void OnCIMMODEChanging(string value);
    partial void OnCIMMODEChanged();
    partial void OnCURRENTRECIPEIDChanging(string value);
    partial void OnCURRENTRECIPEIDChanged();
    partial void OnCURRENTSTATUSChanging(string value);
    partial void OnCURRENTSTATUSChanged();
    partial void OnAUTOMANUELChanging(string value);
    partial void OnAUTOMANUELChanged();
    partial void OnUPINLINEMODEChanging(string value);
    partial void OnUPINLINEMODEChanged();
    partial void OnDOWNINLINEMODEChanging(string value);
    partial void OnDOWNINLINEMODEChanged();
    partial void OnTFTJOBCOUNTChanging(System.Nullable<int> value);
    partial void OnTFTJOBCOUNTChanged();
    partial void OnHFJOBCOUNTChanging(System.Nullable<int> value);
    partial void OnHFJOBCOUNTChanged();
    partial void OnDUMMYJOBCOUNTChanging(System.Nullable<int> value);
    partial void OnDUMMYJOBCOUNTChanged();
    partial void OnUVMASKCOUNTChanging(System.Nullable<int> value);
    partial void OnUVMASKCOUNTChanged();
    partial void OnMQCJOBCOUNTChanging(System.Nullable<int> value);
    partial void OnMQCJOBCOUNTChanged();
    partial void OnPRODUCTTYPEChanging(System.Nullable<int> value);
    partial void OnPRODUCTTYPEChanged();
    partial void OnRECIPECHECKChanging(string value);
    partial void OnRECIPECHECKChanged();
    partial void OnGLASSCHECKMODEChanging(string value);
    partial void OnGLASSCHECKMODEChanged();
    partial void OnRECIPEAUTOCHANGEChanging(string value);
    partial void OnRECIPEAUTOCHANGEChanged();
    partial void OnPRODUCTTYPECHECKMODEChanging(string value);
    partial void OnPRODUCTTYPECHECKMODEChanged();
    partial void OnGROUPINDEXCHECKMODEChanging(string value);
    partial void OnGROUPINDEXCHECKMODEChanged();
    partial void OnPRODUCTIDCHECKMODEChanging(string value);
    partial void OnPRODUCTIDCHECKMODEChanged();
    partial void OnDUPLICATECHECKMODEChanging(string value);
    partial void OnDUPLICATECHECKMODEChanged();
    partial void OnADDLIQUIDChanging(string value);
    partial void OnADDLIQUIDChanged();
    partial void OnMINLIQUIDChanging(string value);
    partial void OnMINLIQUIDChanged();
    partial void OnVCRENBLEChanging(string value);
    partial void OnVCRENBLEChanged();
    partial void OnVCRIDChanging(string value);
    partial void OnVCRIDChanged();
    #endregion
		
		public SBCS_NODEHISTORY()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OBJECTKEY", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long OBJECTKEY
		{
			get
			{
				return this._OBJECTKEY;
			}
			set
			{
				if ((this._OBJECTKEY != value))
				{
					this.OnOBJECTKEYChanging(value);
					this.SendPropertyChanging();
					this._OBJECTKEY = value;
					this.SendPropertyChanged("OBJECTKEY");
					this.OnOBJECTKEYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPDATETIME", DbType="DateTime NOT NULL")]
		public System.DateTime UPDATETIME
		{
			get
			{
				return this._UPDATETIME;
			}
			set
			{
				if ((this._UPDATETIME != value))
				{
					this.OnUPDATETIMEChanging(value);
					this.SendPropertyChanging();
					this._UPDATETIME = value;
					this.SendPropertyChanged("UPDATETIME");
					this.OnUPDATETIMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LINEID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string LINEID
		{
			get
			{
				return this._LINEID;
			}
			set
			{
				if ((this._LINEID != value))
				{
					this.OnLINEIDChanging(value);
					this.SendPropertyChanging();
					this._LINEID = value;
					this.SendPropertyChanged("LINEID");
					this.OnLINEIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NODEID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string NODEID
		{
			get
			{
				return this._NODEID;
			}
			set
			{
				if ((this._NODEID != value))
				{
					this.OnNODEIDChanging(value);
					this.SendPropertyChanging();
					this._NODEID = value;
					this.SendPropertyChanged("NODEID");
					this.OnNODEIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NODENO", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string NODENO
		{
			get
			{
				return this._NODENO;
			}
			set
			{
				if ((this._NODENO != value))
				{
					this.OnNODENOChanging(value);
					this.SendPropertyChanging();
					this._NODENO = value;
					this.SendPropertyChanged("NODENO");
					this.OnNODENOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CIMMODE", DbType="VarChar(50)")]
		public string CIMMODE
		{
			get
			{
				return this._CIMMODE;
			}
			set
			{
				if ((this._CIMMODE != value))
				{
					this.OnCIMMODEChanging(value);
					this.SendPropertyChanging();
					this._CIMMODE = value;
					this.SendPropertyChanged("CIMMODE");
					this.OnCIMMODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CURRENTRECIPEID", DbType="VarChar(50)")]
		public string CURRENTRECIPEID
		{
			get
			{
				return this._CURRENTRECIPEID;
			}
			set
			{
				if ((this._CURRENTRECIPEID != value))
				{
					this.OnCURRENTRECIPEIDChanging(value);
					this.SendPropertyChanging();
					this._CURRENTRECIPEID = value;
					this.SendPropertyChanged("CURRENTRECIPEID");
					this.OnCURRENTRECIPEIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CURRENTSTATUS", DbType="VarChar(50)")]
		public string CURRENTSTATUS
		{
			get
			{
				return this._CURRENTSTATUS;
			}
			set
			{
				if ((this._CURRENTSTATUS != value))
				{
					this.OnCURRENTSTATUSChanging(value);
					this.SendPropertyChanging();
					this._CURRENTSTATUS = value;
					this.SendPropertyChanged("CURRENTSTATUS");
					this.OnCURRENTSTATUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AUTOMANUEL", DbType="VarChar(50)")]
		public string AUTOMANUEL
		{
			get
			{
				return this._AUTOMANUEL;
			}
			set
			{
				if ((this._AUTOMANUEL != value))
				{
					this.OnAUTOMANUELChanging(value);
					this.SendPropertyChanging();
					this._AUTOMANUEL = value;
					this.SendPropertyChanged("AUTOMANUEL");
					this.OnAUTOMANUELChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPINLINEMODE", DbType="VarChar(50)")]
		public string UPINLINEMODE
		{
			get
			{
				return this._UPINLINEMODE;
			}
			set
			{
				if ((this._UPINLINEMODE != value))
				{
					this.OnUPINLINEMODEChanging(value);
					this.SendPropertyChanging();
					this._UPINLINEMODE = value;
					this.SendPropertyChanged("UPINLINEMODE");
					this.OnUPINLINEMODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOWNINLINEMODE", DbType="VarChar(50)")]
		public string DOWNINLINEMODE
		{
			get
			{
				return this._DOWNINLINEMODE;
			}
			set
			{
				if ((this._DOWNINLINEMODE != value))
				{
					this.OnDOWNINLINEMODEChanging(value);
					this.SendPropertyChanging();
					this._DOWNINLINEMODE = value;
					this.SendPropertyChanged("DOWNINLINEMODE");
					this.OnDOWNINLINEMODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TFTJOBCOUNT", DbType="Int")]
		public System.Nullable<int> TFTJOBCOUNT
		{
			get
			{
				return this._TFTJOBCOUNT;
			}
			set
			{
				if ((this._TFTJOBCOUNT != value))
				{
					this.OnTFTJOBCOUNTChanging(value);
					this.SendPropertyChanging();
					this._TFTJOBCOUNT = value;
					this.SendPropertyChanged("TFTJOBCOUNT");
					this.OnTFTJOBCOUNTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HFJOBCOUNT", DbType="Int")]
		public System.Nullable<int> HFJOBCOUNT
		{
			get
			{
				return this._HFJOBCOUNT;
			}
			set
			{
				if ((this._HFJOBCOUNT != value))
				{
					this.OnHFJOBCOUNTChanging(value);
					this.SendPropertyChanging();
					this._HFJOBCOUNT = value;
					this.SendPropertyChanged("HFJOBCOUNT");
					this.OnHFJOBCOUNTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DUMMYJOBCOUNT", DbType="Int")]
		public System.Nullable<int> DUMMYJOBCOUNT
		{
			get
			{
				return this._DUMMYJOBCOUNT;
			}
			set
			{
				if ((this._DUMMYJOBCOUNT != value))
				{
					this.OnDUMMYJOBCOUNTChanging(value);
					this.SendPropertyChanging();
					this._DUMMYJOBCOUNT = value;
					this.SendPropertyChanged("DUMMYJOBCOUNT");
					this.OnDUMMYJOBCOUNTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UVMASKCOUNT", DbType="Int")]
		public System.Nullable<int> UVMASKCOUNT
		{
			get
			{
				return this._UVMASKCOUNT;
			}
			set
			{
				if ((this._UVMASKCOUNT != value))
				{
					this.OnUVMASKCOUNTChanging(value);
					this.SendPropertyChanging();
					this._UVMASKCOUNT = value;
					this.SendPropertyChanged("UVMASKCOUNT");
					this.OnUVMASKCOUNTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MQCJOBCOUNT", DbType="Int")]
		public System.Nullable<int> MQCJOBCOUNT
		{
			get
			{
				return this._MQCJOBCOUNT;
			}
			set
			{
				if ((this._MQCJOBCOUNT != value))
				{
					this.OnMQCJOBCOUNTChanging(value);
					this.SendPropertyChanging();
					this._MQCJOBCOUNT = value;
					this.SendPropertyChanged("MQCJOBCOUNT");
					this.OnMQCJOBCOUNTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRODUCTTYPE", DbType="Int")]
		public System.Nullable<int> PRODUCTTYPE
		{
			get
			{
				return this._PRODUCTTYPE;
			}
			set
			{
				if ((this._PRODUCTTYPE != value))
				{
					this.OnPRODUCTTYPEChanging(value);
					this.SendPropertyChanging();
					this._PRODUCTTYPE = value;
					this.SendPropertyChanged("PRODUCTTYPE");
					this.OnPRODUCTTYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RECIPECHECK", DbType="VarChar(50)")]
		public string RECIPECHECK
		{
			get
			{
				return this._RECIPECHECK;
			}
			set
			{
				if ((this._RECIPECHECK != value))
				{
					this.OnRECIPECHECKChanging(value);
					this.SendPropertyChanging();
					this._RECIPECHECK = value;
					this.SendPropertyChanged("RECIPECHECK");
					this.OnRECIPECHECKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GLASSCHECKMODE", DbType="VarChar(50)")]
		public string GLASSCHECKMODE
		{
			get
			{
				return this._GLASSCHECKMODE;
			}
			set
			{
				if ((this._GLASSCHECKMODE != value))
				{
					this.OnGLASSCHECKMODEChanging(value);
					this.SendPropertyChanging();
					this._GLASSCHECKMODE = value;
					this.SendPropertyChanged("GLASSCHECKMODE");
					this.OnGLASSCHECKMODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RECIPEAUTOCHANGE", DbType="VarChar(50)")]
		public string RECIPEAUTOCHANGE
		{
			get
			{
				return this._RECIPEAUTOCHANGE;
			}
			set
			{
				if ((this._RECIPEAUTOCHANGE != value))
				{
					this.OnRECIPEAUTOCHANGEChanging(value);
					this.SendPropertyChanging();
					this._RECIPEAUTOCHANGE = value;
					this.SendPropertyChanged("RECIPEAUTOCHANGE");
					this.OnRECIPEAUTOCHANGEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRODUCTTYPECHECKMODE", DbType="VarChar(50)")]
		public string PRODUCTTYPECHECKMODE
		{
			get
			{
				return this._PRODUCTTYPECHECKMODE;
			}
			set
			{
				if ((this._PRODUCTTYPECHECKMODE != value))
				{
					this.OnPRODUCTTYPECHECKMODEChanging(value);
					this.SendPropertyChanging();
					this._PRODUCTTYPECHECKMODE = value;
					this.SendPropertyChanged("PRODUCTTYPECHECKMODE");
					this.OnPRODUCTTYPECHECKMODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GROUPINDEXCHECKMODE", DbType="VarChar(50)")]
		public string GROUPINDEXCHECKMODE
		{
			get
			{
				return this._GROUPINDEXCHECKMODE;
			}
			set
			{
				if ((this._GROUPINDEXCHECKMODE != value))
				{
					this.OnGROUPINDEXCHECKMODEChanging(value);
					this.SendPropertyChanging();
					this._GROUPINDEXCHECKMODE = value;
					this.SendPropertyChanged("GROUPINDEXCHECKMODE");
					this.OnGROUPINDEXCHECKMODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRODUCTIDCHECKMODE", DbType="VarChar(50)")]
		public string PRODUCTIDCHECKMODE
		{
			get
			{
				return this._PRODUCTIDCHECKMODE;
			}
			set
			{
				if ((this._PRODUCTIDCHECKMODE != value))
				{
					this.OnPRODUCTIDCHECKMODEChanging(value);
					this.SendPropertyChanging();
					this._PRODUCTIDCHECKMODE = value;
					this.SendPropertyChanged("PRODUCTIDCHECKMODE");
					this.OnPRODUCTIDCHECKMODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DUPLICATECHECKMODE", DbType="VarChar(50)")]
		public string DUPLICATECHECKMODE
		{
			get
			{
				return this._DUPLICATECHECKMODE;
			}
			set
			{
				if ((this._DUPLICATECHECKMODE != value))
				{
					this.OnDUPLICATECHECKMODEChanging(value);
					this.SendPropertyChanging();
					this._DUPLICATECHECKMODE = value;
					this.SendPropertyChanged("DUPLICATECHECKMODE");
					this.OnDUPLICATECHECKMODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADDLIQUID", DbType="VarChar(50)")]
		public string ADDLIQUID
		{
			get
			{
				return this._ADDLIQUID;
			}
			set
			{
				if ((this._ADDLIQUID != value))
				{
					this.OnADDLIQUIDChanging(value);
					this.SendPropertyChanging();
					this._ADDLIQUID = value;
					this.SendPropertyChanged("ADDLIQUID");
					this.OnADDLIQUIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MINLIQUID", DbType="VarChar(50)")]
		public string MINLIQUID
		{
			get
			{
				return this._MINLIQUID;
			}
			set
			{
				if ((this._MINLIQUID != value))
				{
					this.OnMINLIQUIDChanging(value);
					this.SendPropertyChanging();
					this._MINLIQUID = value;
					this.SendPropertyChanged("MINLIQUID");
					this.OnMINLIQUIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VCRENBLE", DbType="VarChar(50)")]
		public string VCRENBLE
		{
			get
			{
				return this._VCRENBLE;
			}
			set
			{
				if ((this._VCRENBLE != value))
				{
					this.OnVCRENBLEChanging(value);
					this.SendPropertyChanging();
					this._VCRENBLE = value;
					this.SendPropertyChanged("VCRENBLE");
					this.OnVCRENBLEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VCRID", DbType="VarChar(50)")]
		public string VCRID
		{
			get
			{
				return this._VCRID;
			}
			set
			{
				if ((this._VCRID != value))
				{
					this.OnVCRIDChanging(value);
					this.SendPropertyChanging();
					this._VCRID = value;
					this.SendPropertyChanged("VCRID");
					this.OnVCRIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SBCS_TANKHISTORY")]
	public partial class SBCS_TANKHISTORY : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _OBJECTKEY;
		
		private string _NODEID;
		
		private string _TANKID;
		
		private string _TANKEVENT;
		
		private System.Nullable<System.DateTime> _STARTTIME;
		
		private System.Nullable<System.DateTime> _ENDTIME;
		
		private string _TOTALTIME;
		
		private string _QUANTITY;
		
		private string _SPEED;
		
		private string _OPERATORID;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnOBJECTKEYChanging(long value);
    partial void OnOBJECTKEYChanged();
    partial void OnNODEIDChanging(string value);
    partial void OnNODEIDChanged();
    partial void OnTANKIDChanging(string value);
    partial void OnTANKIDChanged();
    partial void OnTANKEVENTChanging(string value);
    partial void OnTANKEVENTChanged();
    partial void OnSTARTTIMEChanging(System.Nullable<System.DateTime> value);
    partial void OnSTARTTIMEChanged();
    partial void OnENDTIMEChanging(System.Nullable<System.DateTime> value);
    partial void OnENDTIMEChanged();
    partial void OnTOTALTIMEChanging(string value);
    partial void OnTOTALTIMEChanged();
    partial void OnQUANTITYChanging(string value);
    partial void OnQUANTITYChanged();
    partial void OnSPEEDChanging(string value);
    partial void OnSPEEDChanged();
    partial void OnOPERATORIDChanging(string value);
    partial void OnOPERATORIDChanged();
    #endregion
		
		public SBCS_TANKHISTORY()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OBJECTKEY", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long OBJECTKEY
		{
			get
			{
				return this._OBJECTKEY;
			}
			set
			{
				if ((this._OBJECTKEY != value))
				{
					this.OnOBJECTKEYChanging(value);
					this.SendPropertyChanging();
					this._OBJECTKEY = value;
					this.SendPropertyChanged("OBJECTKEY");
					this.OnOBJECTKEYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NODEID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string NODEID
		{
			get
			{
				return this._NODEID;
			}
			set
			{
				if ((this._NODEID != value))
				{
					this.OnNODEIDChanging(value);
					this.SendPropertyChanging();
					this._NODEID = value;
					this.SendPropertyChanged("NODEID");
					this.OnNODEIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TANKID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string TANKID
		{
			get
			{
				return this._TANKID;
			}
			set
			{
				if ((this._TANKID != value))
				{
					this.OnTANKIDChanging(value);
					this.SendPropertyChanging();
					this._TANKID = value;
					this.SendPropertyChanged("TANKID");
					this.OnTANKIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TANKEVENT", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string TANKEVENT
		{
			get
			{
				return this._TANKEVENT;
			}
			set
			{
				if ((this._TANKEVENT != value))
				{
					this.OnTANKEVENTChanging(value);
					this.SendPropertyChanging();
					this._TANKEVENT = value;
					this.SendPropertyChanged("TANKEVENT");
					this.OnTANKEVENTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STARTTIME", DbType="DateTime")]
		public System.Nullable<System.DateTime> STARTTIME
		{
			get
			{
				return this._STARTTIME;
			}
			set
			{
				if ((this._STARTTIME != value))
				{
					this.OnSTARTTIMEChanging(value);
					this.SendPropertyChanging();
					this._STARTTIME = value;
					this.SendPropertyChanged("STARTTIME");
					this.OnSTARTTIMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ENDTIME", DbType="DateTime")]
		public System.Nullable<System.DateTime> ENDTIME
		{
			get
			{
				return this._ENDTIME;
			}
			set
			{
				if ((this._ENDTIME != value))
				{
					this.OnENDTIMEChanging(value);
					this.SendPropertyChanging();
					this._ENDTIME = value;
					this.SendPropertyChanged("ENDTIME");
					this.OnENDTIMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTALTIME", DbType="VarChar(50)")]
		public string TOTALTIME
		{
			get
			{
				return this._TOTALTIME;
			}
			set
			{
				if ((this._TOTALTIME != value))
				{
					this.OnTOTALTIMEChanging(value);
					this.SendPropertyChanging();
					this._TOTALTIME = value;
					this.SendPropertyChanged("TOTALTIME");
					this.OnTOTALTIMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QUANTITY", DbType="VarChar(50)")]
		public string QUANTITY
		{
			get
			{
				return this._QUANTITY;
			}
			set
			{
				if ((this._QUANTITY != value))
				{
					this.OnQUANTITYChanging(value);
					this.SendPropertyChanging();
					this._QUANTITY = value;
					this.SendPropertyChanged("QUANTITY");
					this.OnQUANTITYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SPEED", DbType="VarChar(50)")]
		public string SPEED
		{
			get
			{
				return this._SPEED;
			}
			set
			{
				if ((this._SPEED != value))
				{
					this.OnSPEEDChanging(value);
					this.SendPropertyChanging();
					this._SPEED = value;
					this.SendPropertyChanged("SPEED");
					this.OnSPEEDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OPERATORID", DbType="VarChar(50)")]
		public string OPERATORID
		{
			get
			{
				return this._OPERATORID;
			}
			set
			{
				if ((this._OPERATORID != value))
				{
					this.OnOPERATORIDChanging(value);
					this.SendPropertyChanging();
					this._OPERATORID = value;
					this.SendPropertyChanged("OPERATORID");
					this.OnOPERATORIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SBCS_RECIPEHISTORY")]
	public partial class SBCS_RECIPEHISTORY : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _OBJECTKEY;
		
		private System.DateTime _UPDATETIME;
		
		private string _NODENAME;
		
		private string _RECIPENO;
		
		private string _RECIPEID;
		
		private System.Nullable<System.DateTime> _CREATETIME;
		
		private string _VERSIONNO;
		
		private string _EVENT;
		
		private string _FILENAME;
		
		private string _OPERATORID;
		
		private string _RECIPESTATUS;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnOBJECTKEYChanging(long value);
    partial void OnOBJECTKEYChanged();
    partial void OnUPDATETIMEChanging(System.DateTime value);
    partial void OnUPDATETIMEChanged();
    partial void OnNODENAMEChanging(string value);
    partial void OnNODENAMEChanged();
    partial void OnRECIPENOChanging(string value);
    partial void OnRECIPENOChanged();
    partial void OnRECIPEIDChanging(string value);
    partial void OnRECIPEIDChanged();
    partial void OnCREATETIMEChanging(System.Nullable<System.DateTime> value);
    partial void OnCREATETIMEChanged();
    partial void OnVERSIONNOChanging(string value);
    partial void OnVERSIONNOChanged();
    partial void OnEVENTChanging(string value);
    partial void OnEVENTChanged();
    partial void OnFILENAMEChanging(string value);
    partial void OnFILENAMEChanged();
    partial void OnOPERATORIDChanging(string value);
    partial void OnOPERATORIDChanged();
    partial void OnRECIPESTATUSChanging(string value);
    partial void OnRECIPESTATUSChanged();
    #endregion
		
		public SBCS_RECIPEHISTORY()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OBJECTKEY", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long OBJECTKEY
		{
			get
			{
				return this._OBJECTKEY;
			}
			set
			{
				if ((this._OBJECTKEY != value))
				{
					this.OnOBJECTKEYChanging(value);
					this.SendPropertyChanging();
					this._OBJECTKEY = value;
					this.SendPropertyChanged("OBJECTKEY");
					this.OnOBJECTKEYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPDATETIME", DbType="DateTime NOT NULL")]
		public System.DateTime UPDATETIME
		{
			get
			{
				return this._UPDATETIME;
			}
			set
			{
				if ((this._UPDATETIME != value))
				{
					this.OnUPDATETIMEChanging(value);
					this.SendPropertyChanging();
					this._UPDATETIME = value;
					this.SendPropertyChanged("UPDATETIME");
					this.OnUPDATETIMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NODENAME", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string NODENAME
		{
			get
			{
				return this._NODENAME;
			}
			set
			{
				if ((this._NODENAME != value))
				{
					this.OnNODENAMEChanging(value);
					this.SendPropertyChanging();
					this._NODENAME = value;
					this.SendPropertyChanged("NODENAME");
					this.OnNODENAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RECIPENO", DbType="VarChar(50)")]
		public string RECIPENO
		{
			get
			{
				return this._RECIPENO;
			}
			set
			{
				if ((this._RECIPENO != value))
				{
					this.OnRECIPENOChanging(value);
					this.SendPropertyChanging();
					this._RECIPENO = value;
					this.SendPropertyChanged("RECIPENO");
					this.OnRECIPENOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RECIPEID", DbType="VarChar(50)")]
		public string RECIPEID
		{
			get
			{
				return this._RECIPEID;
			}
			set
			{
				if ((this._RECIPEID != value))
				{
					this.OnRECIPEIDChanging(value);
					this.SendPropertyChanging();
					this._RECIPEID = value;
					this.SendPropertyChanged("RECIPEID");
					this.OnRECIPEIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATETIME", DbType="DateTime")]
		public System.Nullable<System.DateTime> CREATETIME
		{
			get
			{
				return this._CREATETIME;
			}
			set
			{
				if ((this._CREATETIME != value))
				{
					this.OnCREATETIMEChanging(value);
					this.SendPropertyChanging();
					this._CREATETIME = value;
					this.SendPropertyChanged("CREATETIME");
					this.OnCREATETIMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VERSIONNO", DbType="VarChar(50)")]
		public string VERSIONNO
		{
			get
			{
				return this._VERSIONNO;
			}
			set
			{
				if ((this._VERSIONNO != value))
				{
					this.OnVERSIONNOChanging(value);
					this.SendPropertyChanging();
					this._VERSIONNO = value;
					this.SendPropertyChanged("VERSIONNO");
					this.OnVERSIONNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EVENT", DbType="VarChar(50)")]
		public string EVENT
		{
			get
			{
				return this._EVENT;
			}
			set
			{
				if ((this._EVENT != value))
				{
					this.OnEVENTChanging(value);
					this.SendPropertyChanging();
					this._EVENT = value;
					this.SendPropertyChanged("EVENT");
					this.OnEVENTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FILENAME", DbType="VarChar(500)")]
		public string FILENAME
		{
			get
			{
				return this._FILENAME;
			}
			set
			{
				if ((this._FILENAME != value))
				{
					this.OnFILENAMEChanging(value);
					this.SendPropertyChanging();
					this._FILENAME = value;
					this.SendPropertyChanged("FILENAME");
					this.OnFILENAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OPERATORID", DbType="VarChar(50)")]
		public string OPERATORID
		{
			get
			{
				return this._OPERATORID;
			}
			set
			{
				if ((this._OPERATORID != value))
				{
					this.OnOPERATORIDChanging(value);
					this.SendPropertyChanging();
					this._OPERATORID = value;
					this.SendPropertyChanged("OPERATORID");
					this.OnOPERATORIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RECIPESTATUS", DbType="VarChar(50)")]
		public string RECIPESTATUS
		{
			get
			{
				return this._RECIPESTATUS;
			}
			set
			{
				if ((this._RECIPESTATUS != value))
				{
					this.OnRECIPESTATUSChanging(value);
					this.SendPropertyChanging();
					this._RECIPESTATUS = value;
					this.SendPropertyChanged("RECIPESTATUS");
					this.OnRECIPESTATUSChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SBCS_TACTDATAHISTORY")]
	public partial class SBCS_TACTDATAHISTORY
	{
		
		private long _OBJECTKEY;
		
		private System.Nullable<int> _CASSETTESEQNO;
		
		private System.Nullable<int> _CASSETTESLOTNO;
		
		private string _JOBID;
		
		private System.Nullable<System.DateTime> _UPDATETIME;
		
		private string _FILENAMA;
		
		private string _LOCALPROCESSSTARTTIME;
		
		private string _LOCALPROCSSSENDTIME;
		
		private System.Nullable<int> _PROCESSTIME;
		
		public SBCS_TACTDATAHISTORY()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OBJECTKEY", AutoSync=AutoSync.Always, DbType="BigInt NOT NULL IDENTITY", IsDbGenerated=true)]
		public long OBJECTKEY
		{
			get
			{
				return this._OBJECTKEY;
			}
			set
			{
				if ((this._OBJECTKEY != value))
				{
					this._OBJECTKEY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CASSETTESEQNO", DbType="Int")]
		public System.Nullable<int> CASSETTESEQNO
		{
			get
			{
				return this._CASSETTESEQNO;
			}
			set
			{
				if ((this._CASSETTESEQNO != value))
				{
					this._CASSETTESEQNO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CASSETTESLOTNO", DbType="Int")]
		public System.Nullable<int> CASSETTESLOTNO
		{
			get
			{
				return this._CASSETTESLOTNO;
			}
			set
			{
				if ((this._CASSETTESLOTNO != value))
				{
					this._CASSETTESLOTNO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JOBID", DbType="VarChar(50)")]
		public string JOBID
		{
			get
			{
				return this._JOBID;
			}
			set
			{
				if ((this._JOBID != value))
				{
					this._JOBID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPDATETIME", DbType="DateTime")]
		public System.Nullable<System.DateTime> UPDATETIME
		{
			get
			{
				return this._UPDATETIME;
			}
			set
			{
				if ((this._UPDATETIME != value))
				{
					this._UPDATETIME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FILENAMA", DbType="VarChar(100)")]
		public string FILENAMA
		{
			get
			{
				return this._FILENAMA;
			}
			set
			{
				if ((this._FILENAMA != value))
				{
					this._FILENAMA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOCALPROCESSSTARTTIME", DbType="VarChar(50)")]
		public string LOCALPROCESSSTARTTIME
		{
			get
			{
				return this._LOCALPROCESSSTARTTIME;
			}
			set
			{
				if ((this._LOCALPROCESSSTARTTIME != value))
				{
					this._LOCALPROCESSSTARTTIME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOCALPROCSSSENDTIME", DbType="VarChar(50)")]
		public string LOCALPROCSSSENDTIME
		{
			get
			{
				return this._LOCALPROCSSSENDTIME;
			}
			set
			{
				if ((this._LOCALPROCSSSENDTIME != value))
				{
					this._LOCALPROCSSSENDTIME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROCESSTIME", DbType="Int")]
		public System.Nullable<int> PROCESSTIME
		{
			get
			{
				return this._PROCESSTIME;
			}
			set
			{
				if ((this._PROCESSTIME != value))
				{
					this._PROCESSTIME = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SBCS_JOBHISTORY")]
	public partial class SBCS_JOBHISTORY : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _OBJECTKEY;
		
		private System.Nullable<System.DateTime> _UPDATETIME;
		
		private string _EVENTNAME;
		
		private string _CASSETTESEQNO;
		
		private string _CASSETTESLOTNO;
		
		private string _NODENO;
		
		private string _UNITNO;
		
		private string _JOBID;
		
		private string _GROUPNUMBER;
		
		private string _GLASSTYPE;
		
		private string _GLASSJUDGE;
		
		private string _PROCESSSKIPFLAG;
		
		private string _LASTGLASSFLAG;
		
		private string _CIMMODECREATE;
		
		private string _SAMPLINGFLAG;
		
		private string _RESERVED;
		
		private string _INSPECTIONJUDGERESULT;
		
		private string _INSPECTIONRESERVATIONSIGNAL;
		
		private string _PROCESSRESERVATIONSIGNAL;
		
		private string _TRACKINGDATAHISTORY;
		
		private string _EQUIPMENTSPECIALFLAG;
		
		private string _GLASSID;
		
		private string _SORTERGRADE;
		
		private string _GLASSGRADE;
		
		private string _FROMPORTNO;
		
		private string _TARGETPORTNO;
		
		private string _TARGETSLOTNO;
		
		private string _TARGETCASSETTEID;
		
		private string _RESERVE;
		
		private string _PPID;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnOBJECTKEYChanging(long value);
    partial void OnOBJECTKEYChanged();
    partial void OnUPDATETIMEChanging(System.Nullable<System.DateTime> value);
    partial void OnUPDATETIMEChanged();
    partial void OnEVENTNAMEChanging(string value);
    partial void OnEVENTNAMEChanged();
    partial void OnCASSETTESEQNOChanging(string value);
    partial void OnCASSETTESEQNOChanged();
    partial void OnCASSETTESLOTNOChanging(string value);
    partial void OnCASSETTESLOTNOChanged();
    partial void OnNODENOChanging(string value);
    partial void OnNODENOChanged();
    partial void OnUNITNOChanging(string value);
    partial void OnUNITNOChanged();
    partial void OnJOBIDChanging(string value);
    partial void OnJOBIDChanged();
    partial void OnGROUPNUMBERChanging(string value);
    partial void OnGROUPNUMBERChanged();
    partial void OnGLASSTYPEChanging(string value);
    partial void OnGLASSTYPEChanged();
    partial void OnGLASSJUDGEChanging(string value);
    partial void OnGLASSJUDGEChanged();
    partial void OnPROCESSSKIPFLAGChanging(string value);
    partial void OnPROCESSSKIPFLAGChanged();
    partial void OnLASTGLASSFLAGChanging(string value);
    partial void OnLASTGLASSFLAGChanged();
    partial void OnCIMMODECREATEChanging(string value);
    partial void OnCIMMODECREATEChanged();
    partial void OnSAMPLINGFLAGChanging(string value);
    partial void OnSAMPLINGFLAGChanged();
    partial void OnRESERVEDChanging(string value);
    partial void OnRESERVEDChanged();
    partial void OnINSPECTIONJUDGERESULTChanging(string value);
    partial void OnINSPECTIONJUDGERESULTChanged();
    partial void OnINSPECTIONRESERVATIONSIGNALChanging(string value);
    partial void OnINSPECTIONRESERVATIONSIGNALChanged();
    partial void OnPROCESSRESERVATIONSIGNALChanging(string value);
    partial void OnPROCESSRESERVATIONSIGNALChanged();
    partial void OnTRACKINGDATAHISTORYChanging(string value);
    partial void OnTRACKINGDATAHISTORYChanged();
    partial void OnEQUIPMENTSPECIALFLAGChanging(string value);
    partial void OnEQUIPMENTSPECIALFLAGChanged();
    partial void OnGLASSIDChanging(string value);
    partial void OnGLASSIDChanged();
    partial void OnSORTERGRADEChanging(string value);
    partial void OnSORTERGRADEChanged();
    partial void OnGLASSGRADEChanging(string value);
    partial void OnGLASSGRADEChanged();
    partial void OnFROMPORTNOChanging(string value);
    partial void OnFROMPORTNOChanged();
    partial void OnTARGETPORTNOChanging(string value);
    partial void OnTARGETPORTNOChanged();
    partial void OnTARGETSLOTNOChanging(string value);
    partial void OnTARGETSLOTNOChanged();
    partial void OnTARGETCASSETTEIDChanging(string value);
    partial void OnTARGETCASSETTEIDChanged();
    partial void OnRESERVEChanging(string value);
    partial void OnRESERVEChanged();
    partial void OnPPIDChanging(string value);
    partial void OnPPIDChanged();
    #endregion
		
		public SBCS_JOBHISTORY()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OBJECTKEY", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long OBJECTKEY
		{
			get
			{
				return this._OBJECTKEY;
			}
			set
			{
				if ((this._OBJECTKEY != value))
				{
					this.OnOBJECTKEYChanging(value);
					this.SendPropertyChanging();
					this._OBJECTKEY = value;
					this.SendPropertyChanged("OBJECTKEY");
					this.OnOBJECTKEYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPDATETIME", DbType="DateTime")]
		public System.Nullable<System.DateTime> UPDATETIME
		{
			get
			{
				return this._UPDATETIME;
			}
			set
			{
				if ((this._UPDATETIME != value))
				{
					this.OnUPDATETIMEChanging(value);
					this.SendPropertyChanging();
					this._UPDATETIME = value;
					this.SendPropertyChanged("UPDATETIME");
					this.OnUPDATETIMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EVENTNAME", DbType="VarChar(50)")]
		public string EVENTNAME
		{
			get
			{
				return this._EVENTNAME;
			}
			set
			{
				if ((this._EVENTNAME != value))
				{
					this.OnEVENTNAMEChanging(value);
					this.SendPropertyChanging();
					this._EVENTNAME = value;
					this.SendPropertyChanged("EVENTNAME");
					this.OnEVENTNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CASSETTESEQNO", DbType="VarChar(50)")]
		public string CASSETTESEQNO
		{
			get
			{
				return this._CASSETTESEQNO;
			}
			set
			{
				if ((this._CASSETTESEQNO != value))
				{
					this.OnCASSETTESEQNOChanging(value);
					this.SendPropertyChanging();
					this._CASSETTESEQNO = value;
					this.SendPropertyChanged("CASSETTESEQNO");
					this.OnCASSETTESEQNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CASSETTESLOTNO", DbType="VarChar(50)")]
		public string CASSETTESLOTNO
		{
			get
			{
				return this._CASSETTESLOTNO;
			}
			set
			{
				if ((this._CASSETTESLOTNO != value))
				{
					this.OnCASSETTESLOTNOChanging(value);
					this.SendPropertyChanging();
					this._CASSETTESLOTNO = value;
					this.SendPropertyChanged("CASSETTESLOTNO");
					this.OnCASSETTESLOTNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NODENO", DbType="NVarChar(50)")]
		public string NODENO
		{
			get
			{
				return this._NODENO;
			}
			set
			{
				if ((this._NODENO != value))
				{
					this.OnNODENOChanging(value);
					this.SendPropertyChanging();
					this._NODENO = value;
					this.SendPropertyChanged("NODENO");
					this.OnNODENOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UNITNO", DbType="VarChar(50)")]
		public string UNITNO
		{
			get
			{
				return this._UNITNO;
			}
			set
			{
				if ((this._UNITNO != value))
				{
					this.OnUNITNOChanging(value);
					this.SendPropertyChanging();
					this._UNITNO = value;
					this.SendPropertyChanged("UNITNO");
					this.OnUNITNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JOBID", DbType="VarChar(50)")]
		public string JOBID
		{
			get
			{
				return this._JOBID;
			}
			set
			{
				if ((this._JOBID != value))
				{
					this.OnJOBIDChanging(value);
					this.SendPropertyChanging();
					this._JOBID = value;
					this.SendPropertyChanged("JOBID");
					this.OnJOBIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GROUPNUMBER", DbType="VarChar(50)")]
		public string GROUPNUMBER
		{
			get
			{
				return this._GROUPNUMBER;
			}
			set
			{
				if ((this._GROUPNUMBER != value))
				{
					this.OnGROUPNUMBERChanging(value);
					this.SendPropertyChanging();
					this._GROUPNUMBER = value;
					this.SendPropertyChanged("GROUPNUMBER");
					this.OnGROUPNUMBERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GLASSTYPE", DbType="VarChar(50)")]
		public string GLASSTYPE
		{
			get
			{
				return this._GLASSTYPE;
			}
			set
			{
				if ((this._GLASSTYPE != value))
				{
					this.OnGLASSTYPEChanging(value);
					this.SendPropertyChanging();
					this._GLASSTYPE = value;
					this.SendPropertyChanged("GLASSTYPE");
					this.OnGLASSTYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GLASSJUDGE", DbType="VarChar(50)")]
		public string GLASSJUDGE
		{
			get
			{
				return this._GLASSJUDGE;
			}
			set
			{
				if ((this._GLASSJUDGE != value))
				{
					this.OnGLASSJUDGEChanging(value);
					this.SendPropertyChanging();
					this._GLASSJUDGE = value;
					this.SendPropertyChanged("GLASSJUDGE");
					this.OnGLASSJUDGEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROCESSSKIPFLAG", DbType="VarChar(50)")]
		public string PROCESSSKIPFLAG
		{
			get
			{
				return this._PROCESSSKIPFLAG;
			}
			set
			{
				if ((this._PROCESSSKIPFLAG != value))
				{
					this.OnPROCESSSKIPFLAGChanging(value);
					this.SendPropertyChanging();
					this._PROCESSSKIPFLAG = value;
					this.SendPropertyChanged("PROCESSSKIPFLAG");
					this.OnPROCESSSKIPFLAGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LASTGLASSFLAG", DbType="VarChar(50)")]
		public string LASTGLASSFLAG
		{
			get
			{
				return this._LASTGLASSFLAG;
			}
			set
			{
				if ((this._LASTGLASSFLAG != value))
				{
					this.OnLASTGLASSFLAGChanging(value);
					this.SendPropertyChanging();
					this._LASTGLASSFLAG = value;
					this.SendPropertyChanged("LASTGLASSFLAG");
					this.OnLASTGLASSFLAGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CIMMODECREATE", DbType="VarChar(50)")]
		public string CIMMODECREATE
		{
			get
			{
				return this._CIMMODECREATE;
			}
			set
			{
				if ((this._CIMMODECREATE != value))
				{
					this.OnCIMMODECREATEChanging(value);
					this.SendPropertyChanging();
					this._CIMMODECREATE = value;
					this.SendPropertyChanged("CIMMODECREATE");
					this.OnCIMMODECREATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SAMPLINGFLAG", DbType="VarChar(50)")]
		public string SAMPLINGFLAG
		{
			get
			{
				return this._SAMPLINGFLAG;
			}
			set
			{
				if ((this._SAMPLINGFLAG != value))
				{
					this.OnSAMPLINGFLAGChanging(value);
					this.SendPropertyChanging();
					this._SAMPLINGFLAG = value;
					this.SendPropertyChanged("SAMPLINGFLAG");
					this.OnSAMPLINGFLAGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RESERVED", DbType="VarChar(50)")]
		public string RESERVED
		{
			get
			{
				return this._RESERVED;
			}
			set
			{
				if ((this._RESERVED != value))
				{
					this.OnRESERVEDChanging(value);
					this.SendPropertyChanging();
					this._RESERVED = value;
					this.SendPropertyChanged("RESERVED");
					this.OnRESERVEDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INSPECTIONJUDGERESULT", DbType="VarChar(50)")]
		public string INSPECTIONJUDGERESULT
		{
			get
			{
				return this._INSPECTIONJUDGERESULT;
			}
			set
			{
				if ((this._INSPECTIONJUDGERESULT != value))
				{
					this.OnINSPECTIONJUDGERESULTChanging(value);
					this.SendPropertyChanging();
					this._INSPECTIONJUDGERESULT = value;
					this.SendPropertyChanged("INSPECTIONJUDGERESULT");
					this.OnINSPECTIONJUDGERESULTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INSPECTIONRESERVATIONSIGNAL", DbType="VarChar(50)")]
		public string INSPECTIONRESERVATIONSIGNAL
		{
			get
			{
				return this._INSPECTIONRESERVATIONSIGNAL;
			}
			set
			{
				if ((this._INSPECTIONRESERVATIONSIGNAL != value))
				{
					this.OnINSPECTIONRESERVATIONSIGNALChanging(value);
					this.SendPropertyChanging();
					this._INSPECTIONRESERVATIONSIGNAL = value;
					this.SendPropertyChanged("INSPECTIONRESERVATIONSIGNAL");
					this.OnINSPECTIONRESERVATIONSIGNALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROCESSRESERVATIONSIGNAL", DbType="VarChar(50)")]
		public string PROCESSRESERVATIONSIGNAL
		{
			get
			{
				return this._PROCESSRESERVATIONSIGNAL;
			}
			set
			{
				if ((this._PROCESSRESERVATIONSIGNAL != value))
				{
					this.OnPROCESSRESERVATIONSIGNALChanging(value);
					this.SendPropertyChanging();
					this._PROCESSRESERVATIONSIGNAL = value;
					this.SendPropertyChanged("PROCESSRESERVATIONSIGNAL");
					this.OnPROCESSRESERVATIONSIGNALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRACKINGDATAHISTORY", DbType="VarChar(50)")]
		public string TRACKINGDATAHISTORY
		{
			get
			{
				return this._TRACKINGDATAHISTORY;
			}
			set
			{
				if ((this._TRACKINGDATAHISTORY != value))
				{
					this.OnTRACKINGDATAHISTORYChanging(value);
					this.SendPropertyChanging();
					this._TRACKINGDATAHISTORY = value;
					this.SendPropertyChanged("TRACKINGDATAHISTORY");
					this.OnTRACKINGDATAHISTORYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EQUIPMENTSPECIALFLAG", DbType="VarChar(50)")]
		public string EQUIPMENTSPECIALFLAG
		{
			get
			{
				return this._EQUIPMENTSPECIALFLAG;
			}
			set
			{
				if ((this._EQUIPMENTSPECIALFLAG != value))
				{
					this.OnEQUIPMENTSPECIALFLAGChanging(value);
					this.SendPropertyChanging();
					this._EQUIPMENTSPECIALFLAG = value;
					this.SendPropertyChanged("EQUIPMENTSPECIALFLAG");
					this.OnEQUIPMENTSPECIALFLAGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GLASSID", DbType="VarChar(50)")]
		public string GLASSID
		{
			get
			{
				return this._GLASSID;
			}
			set
			{
				if ((this._GLASSID != value))
				{
					this.OnGLASSIDChanging(value);
					this.SendPropertyChanging();
					this._GLASSID = value;
					this.SendPropertyChanged("GLASSID");
					this.OnGLASSIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SORTERGRADE", DbType="VarChar(50)")]
		public string SORTERGRADE
		{
			get
			{
				return this._SORTERGRADE;
			}
			set
			{
				if ((this._SORTERGRADE != value))
				{
					this.OnSORTERGRADEChanging(value);
					this.SendPropertyChanging();
					this._SORTERGRADE = value;
					this.SendPropertyChanged("SORTERGRADE");
					this.OnSORTERGRADEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GLASSGRADE", DbType="VarChar(50)")]
		public string GLASSGRADE
		{
			get
			{
				return this._GLASSGRADE;
			}
			set
			{
				if ((this._GLASSGRADE != value))
				{
					this.OnGLASSGRADEChanging(value);
					this.SendPropertyChanging();
					this._GLASSGRADE = value;
					this.SendPropertyChanged("GLASSGRADE");
					this.OnGLASSGRADEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FROMPORTNO", DbType="VarChar(50)")]
		public string FROMPORTNO
		{
			get
			{
				return this._FROMPORTNO;
			}
			set
			{
				if ((this._FROMPORTNO != value))
				{
					this.OnFROMPORTNOChanging(value);
					this.SendPropertyChanging();
					this._FROMPORTNO = value;
					this.SendPropertyChanged("FROMPORTNO");
					this.OnFROMPORTNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TARGETPORTNO", DbType="VarChar(50)")]
		public string TARGETPORTNO
		{
			get
			{
				return this._TARGETPORTNO;
			}
			set
			{
				if ((this._TARGETPORTNO != value))
				{
					this.OnTARGETPORTNOChanging(value);
					this.SendPropertyChanging();
					this._TARGETPORTNO = value;
					this.SendPropertyChanged("TARGETPORTNO");
					this.OnTARGETPORTNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TARGETSLOTNO", DbType="VarChar(50)")]
		public string TARGETSLOTNO
		{
			get
			{
				return this._TARGETSLOTNO;
			}
			set
			{
				if ((this._TARGETSLOTNO != value))
				{
					this.OnTARGETSLOTNOChanging(value);
					this.SendPropertyChanging();
					this._TARGETSLOTNO = value;
					this.SendPropertyChanged("TARGETSLOTNO");
					this.OnTARGETSLOTNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TARGETCASSETTEID", DbType="VarChar(50)")]
		public string TARGETCASSETTEID
		{
			get
			{
				return this._TARGETCASSETTEID;
			}
			set
			{
				if ((this._TARGETCASSETTEID != value))
				{
					this.OnTARGETCASSETTEIDChanging(value);
					this.SendPropertyChanging();
					this._TARGETCASSETTEID = value;
					this.SendPropertyChanged("TARGETCASSETTEID");
					this.OnTARGETCASSETTEIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RESERVE", DbType="VarChar(50)")]
		public string RESERVE
		{
			get
			{
				return this._RESERVE;
			}
			set
			{
				if ((this._RESERVE != value))
				{
					this.OnRESERVEChanging(value);
					this.SendPropertyChanging();
					this._RESERVE = value;
					this.SendPropertyChanged("RESERVE");
					this.OnRESERVEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PPID", DbType="VarChar(50)")]
		public string PPID
		{
			get
			{
				return this._PPID;
			}
			set
			{
				if ((this._PPID != value))
				{
					this.OnPPIDChanging(value);
					this.SendPropertyChanging();
					this._PPID = value;
					this.SendPropertyChanged("PPID");
					this.OnPPIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
