<?xml version="1.0" encoding="utf-8"?><Database Name="KZONE_B20_01_HIS" Class="DBHISSETDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=KZONE_B20_01_HIS;Integrated Security=True" SettingsObjectName="KZONE.UI.Properties.Settings" SettingsPropertyName="UniBCS_HKC_HISConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.SBCS_CIMMESSAGEHISTORY" Member="SBCS_CIMMESSAGEHISTORY">
    <Type Name="SBCS_CIMMESSAGEHISTORY">
      <Column Name="OBJECTKEY" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UPDATETIME" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="NODEID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NODENO" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MESSAGEID" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="MESSAGETEXT" Type="System.String" DbType="VarChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="MESSAGESTATUS" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="OPERATORID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="REMARK" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SBCS_PROCESSDATAHISTORY" Member="SBCS_PROCESSDATAHISTORY">
    <Type Name="SBCS_PROCESSDATAHISTORY">
      <Column Name="OBJECTKEY" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CASSETTESEQNO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CASSETTESLOTNO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="JOBID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TRXID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MESCONTROLSTATE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NODEID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UPDATETIME" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FILENAMA" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="LOCALPROCESSSTARTTIME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LOCALPROCSSSENDTIME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PROCESSTIME" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SBCS_UNITHISTORY" Member="SBCS_UNITHISTORY">
    <Type Name="SBCS_UNITHISTORY">
      <Column Name="OBJECTKEY" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UPDATETIME" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="NODEID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NODENO" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UNITNO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UNITID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UNITSTATUS" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UNITTYPE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UNITRECIPEID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SBCS_ALARMHISTORY" Member="SBCS_ALARMHISTORY">
    <Type Name="SBCS_ALARMHISTORY">
      <Column Name="OBJECTKEY" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EVENTNAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UPDATETIME" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ALARMID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ALARMADDRESS" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ALARMCODE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ALARMLEVEL" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ALARMTEXT" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="ALARMSTATUS" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NODEID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ALARMUNIT" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SBCS_NODEHISTORY" Member="SBCS_NODEHISTORY">
    <Type Name="SBCS_NODEHISTORY">
      <Column Name="OBJECTKEY" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UPDATETIME" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LINEID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NODEID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NODENO" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CIMMODE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CURRENTRECIPEID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CURRENTSTATUS" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="AUTOMANUEL" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UPINLINEMODE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DOWNINLINEMODE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TFTJOBCOUNT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HFJOBCOUNT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DUMMYJOBCOUNT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UVMASKCOUNT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MQCJOBCOUNT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PRODUCTTYPE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RECIPECHECK" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="GLASSCHECKMODE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="RECIPEAUTOCHANGE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PRODUCTTYPECHECKMODE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="GROUPINDEXCHECKMODE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PRODUCTIDCHECKMODE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DUPLICATECHECKMODE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ADDLIQUID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MINLIQUID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="VCRENBLE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="VCRID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SBCS_TANKHISTORY" Member="SBCS_TANKHISTORY">
    <Type Name="SBCS_TANKHISTORY">
      <Column Name="OBJECTKEY" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NODEID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TANKID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TANKEVENT" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="STARTTIME" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ENDTIME" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TOTALTIME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="QUANTITY" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SPEED" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="OPERATORID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SBCS_RECIPEHISTORY" Member="SBCS_RECIPEHISTORY">
    <Type Name="SBCS_RECIPEHISTORY">
      <Column Name="OBJECTKEY" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UPDATETIME" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="NODENAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="RECIPENO" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="RECIPEID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CREATETIME" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="VERSIONNO" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EVENT" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FILENAME" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="OPERATORID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="RECIPESTATUS" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SBCS_TACTDATAHISTORY" Member="SBCS_TACTDATAHISTORY">
    <Type Name="SBCS_TACTDATAHISTORY">
      <Column Name="OBJECTKEY" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CASSETTESEQNO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CASSETTESLOTNO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="JOBID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UPDATETIME" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FILENAMA" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="LOCALPROCESSSTARTTIME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LOCALPROCSSSENDTIME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PROCESSTIME" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SBCS_JOBHISTORY" Member="SBCS_JOBHISTORY">
    <Type Name="SBCS_JOBHISTORY">
      <Column Name="OBJECTKEY" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UPDATETIME" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EVENTNAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NODENO" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UNITNO" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Cassette_Sequence_No" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Job_Sequence_No" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="GlassID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Lot_ID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Product_ID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Operation_ID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CST_Operation_Mode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Substrate_Type" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Product_Type" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Job_Type" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Dummy_Type" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Skip_Flag" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Process_Flag" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Process_Reason_Code" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LOT_Code" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Glass_Thickness" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Glass_Degree" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Inspection_Flag" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Job_Judge" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Job_Grade" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Job_Recovery_Flag" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Mode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Step_ID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="VCR_Read_ID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Master_Recipe_ID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PPID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SBCS_MATERIALHISTORY" Member="SBCS_MATERIALHISTORY">
    <Type Name="SBCS_MATERIALHISTORY">
      <Column Name="OBJECTKEY" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NODEID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UNITNO" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="UPDATETIME" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="MATERIALID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MATERIALCOUNT" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MATERIALSTATUS" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MATERIALTYPE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="OPERATORID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EVENT" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="OLDMATERIALID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FILENAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SBCS_RECIPEVALIDATIONRESULTHISTORY" Member="SBCS_RECIPEVALIDATIONRESULTHISTORY">
    <Type Name="SBCS_RECIPEVALIDATIONRESULTHISTORY">
      <Column Name="NO" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RECEIVETIME" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MASTERRECIPEID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LOCALRECIPEID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="RMS_RESULT" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="RMS_RESULTTEXT" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>