using System;

namespace KZONE.PLCAgent.PLC
{
	/// <summary>
	/// plcdriver errorcode constant define
	/// </summary>
	internal class DriverErrorConst
	{
		public const int DRIVER_INIT_ARGUMENT_IS_NULL_OR_EMPTY_ERR = 20001;

		public const int DRIVER_INIT_ARGUMENT_IS_INVALID_ERR = 20002;

		public const int DRIVER_CREATEADAPTERS_MISSING_REQUIRED_ADAPTER_SETTING_ERR = 20101;

		public const int DRIVER_OPERATION_DRIVER_OBJECT_IS_DISPOSED_ERR = 20201;

		public const int DRIVER_OPERATION_FAIL_TO_MERGE_EVENT_ERR = 20202;

		public const int DRIVER_OPERATION_DRIVER_NOT_INIT_ERR = 20203;

		public const int DRIVER_DECODETRX_FAIL_TO_GET_IODATA_ERR = 20301;

		public const int DRIVER_DECODETRX_EXCEPTION_OCCURE_ERR = 20302;

		public const int DRIVER_DECODEDIRECTREADTRX_EXCEPTION_OCCURE_ERR = 20303;

		public const int DRIVER_GETITEMVALUE_FAIL_TO_GET_ITEM_VAL_ERR = 20401;

		public const int DRIVER_GETITEMVALUE0_FAIL_TO_GET_ITEM_VAL_ERR = 20402;

		public const int DRIVER_GETITEMVALUE_EXCEPTION_OCCURE_ERR = 20403;

		public const int DRIVER_SETITEMVALUE_FAIL_TO_SET_ITEM_VAL_ERR = 20501;

		public const int DRIVER_SCANPROC_WATCHDATA_FAIL_TO_PUTDATA_ERR = 20601;

		public const int DRIVER_SCANPROC_WATCHDATA_FAIL_TO_COPYNEWSNAPSHOTTEMP_ERR = 20602;

		public const int DRIVER_ENCODETRX_EXCEPTION_OCCURE_ERR = 20701;

		public const int DRIVER_ENCODETRX_EVT_RAWDATA_IS_NULL_ERR = 20702;

		public const int DRIVER_ENCODETRX_EVT_RAWDATA_LENGTH_ERR = 20702;

		public const int DRIVER_DIRECTREADCOMPLETE_EXCEPTION_OCCURE_ERR = 20801;

		public const int DRIVER_WRITECOMPLETE_EXCEPTION_OCCURE_ERR = 20901;

		public const int DRIVER_SCANPROC_EXCEPTION_OCCURE_ERR = 20902;

		public const int DRIVER_WRITEPROC_EXCEPTION_OCCURE_ERR = 20903;

		public const int DRIVER_FIREWRITETRXRESULTEVENT_EXCEPTION_OCCURE_ERR = 20904;

		public const int DRIVER_DOTRXWRITE_EMPTY_REQS_ERR = 21001;
	}
}
