<?xml version="1.0" encoding="utf-8"?><Database Name="KZONE_B20_01" Class="DBSETDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=KZONE_B20_01;Integrated Security=True" SettingsObjectName="KZONE.UI.Properties.Settings" SettingsPropertyName="UniBCS_HKCConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.SBRM_OPI_USER_ACCOUNT" Member="SBRM_OPI_USER_ACCOUNT">
    <Type Name="SBRM_OPI_USER_ACCOUNT">
      <Column Name="USER_ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CLIENT_KEY" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="USER_NAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PASSWORD" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="GROUP_ID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="E_MAIL" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LOCAL_NAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DEFAULT_FACTORY_NAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DEFAULT_AREA_NAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ACTIVE" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="UACACTIVE" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="SP1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SP2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SP3" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TRX_DATETIME" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TRX_USER_ID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ADD_DATETIME" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ADD_USER_ID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SBRM_DAILYCHECKDATA" Member="SBRM_DAILYCHECKDATA">
    <Type Name="SBRM_DAILYCHECKDATA">
      <Column Name="OBJECTKEY" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LINETYPE" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LINEID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SERVERNAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NODENO" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SVID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PARAMETERNAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ITEM" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SITE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DESCRIPTION" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="RANGE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="OPERATOR" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DOTRATIO" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="REPORTTO" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="REPORTUNITNO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UNIT" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EXPRESSION" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="WOFFSET" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="WPOINTS" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="BOFFSET" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="BPOINTS" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="JOBDATAITEMNAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SBRM_FDCDATA" Member="SBRM_FDCDATA">
    <Type Name="SBRM_FDCDATA">
      <Column Name="OBJECTKEY" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LINETYPE" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LINEID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SERVERNAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NODENO" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SVID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PARAMETERNAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ITEM" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SITE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DESCRIPTION" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="RANGE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="OPERATOR" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DOTRATIO" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="REPORTTO" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="REPORTUNITNO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UNIT" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EXPRESSION" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="WOFFSET" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="WPOINTS" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="BOFFSET" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="BPOINTS" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="JOBDATAITEMNAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SBRM_HISTABLEFIELDS" Member="SBRM_HISTABLEFIELDS">
    <Type Name="SBRM_HISTABLEFIELDS">
      <Column Name="OBJECTKEY" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="HISTORYTYPE" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TABLENAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TIMESTAMPFIELD" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="QUERYFIELDS" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="DISPLAYFIELDS" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="FIELDWIDTH" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="SORTFIELDS" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SBRM_HISTABLEPARAM" Member="SBRM_HISTABLEPARAM">
    <Type Name="SBRM_HISTABLEPARAM">
      <Column Name="OBJECTKEY" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="HISTORYTYPE" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TABLENAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FIELDKEY" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FIELDCAPTION" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FIELDTYPE" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FIELDDISPLAY" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="FIELDVALUE" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="FIELDDEFAULT" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FIELDCOMBOSQL" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="FIELDCOMBORELATION" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FIELDSEQUENCE" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FIELDATTRIBUTE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ITEMCONDITION" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SBRM_LINE" Member="SBRM_LINE">
    <Type Name="SBRM_LINE">
      <Column Name="OBJECTKEY" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LINEID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LINENAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LINETYPE" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FABTYPE" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SERVERNAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ATTRIBUTE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="JOBDATALINETYPE" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NEXTLINEID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CHECKCROSSRECIPE" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="HISTORYTYPE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="OPI_FUNCTION" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SBRM_NODE" Member="SBRM_NODE">
    <Type Name="SBRM_NODE">
      <Column Name="OBJECTKEY" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LINEID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SERVERNAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NODENO" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NODEID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="REPORTMODE" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ATTRIBUTE" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="RECIPEIDX" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RECIPELEN" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RECIPESEQ" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="UNITCOUNT" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NODENAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="RECIPEREGVALIDATIONENABLED" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="USERUNMODE" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="USEINDEXERMODE" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="USEEDCREPORT" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="DCRCOUNT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DISPATCHCOUNT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="STOPBITCOUNT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OPITYPE" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="EQPPROFILE" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="RECIPEPARAVALIDATIONENABLED" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="FDCREPORT" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="FDCREPORTTIME" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DAILYCHECKREPORT" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="DAILYCHECKREPORTTIME" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SBRM_OPI_PARAMETER" Member="SBRM_OPI_PARAMETER">
    <Type Name="SBRM_OPI_PARAMETER">
      <Column Name="OBJECTKEY" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LINEID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LINETYPE" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="KEYWORD" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SUBKEY" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ITEMVALUE" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="DESCRIPTION" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CONDITION" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SBRM_OPI_USER_ACCOUNT" Member="SBRM_OPI_USER_ACCOUNT1">
    <Type Name="SBRM_OPI_USER_ACCOUNT1">
      <Column Name="USER_ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CLIENT_KEY" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="USER_NAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PASSWORD" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="GROUP_ID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="E_MAIL" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LOCAL_NAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DEFAULT_FACTORY_NAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DEFAULT_AREA_NAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ACTIVE" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="UACACTIVE" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="SP1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SP2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SP3" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TRX_DATETIME" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TRX_USER_ID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ADD_DATETIME" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ADD_USER_ID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SBRM_OPI_USER_GROUP" Member="SBRM_OPI_USER_GROUP">
    <Type Name="SBRM_OPI_USER_GROUP">
      <Column Name="GROUP_ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GROUP_NAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="BUTTON_KEY" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="VISIBLE" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="ENABLE" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.SBRM_POSITION" Member="SBRM_POSITION">
    <Type Name="SBRM_POSITION">
      <Column Name="OBJECTKEY" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="LINEID" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="NODENO" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="UNITTYPE" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="UNITNO" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="POSITIONNO" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="POSITIONNAME" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SBRM_PROCESSDATA" Member="SBRM_PROCESSDATA">
    <Type Name="SBRM_PROCESSDATA">
      <Column Name="OBJECTKEY" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="LINETYPE" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="LINEID" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="SERVERNAME" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="NODENO" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="SVID" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="PARAMETERNAME" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ITEM" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="SITE" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="DESCRIPTION" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="RANGE" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="OPERATOR" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="DOTRATIO" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="REPORTTO" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="REPORTUNITNO" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="UNIT" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="EXPRESSION" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="WOFFSET" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="WPOINTS" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="BOFFSET" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="BPOINTS" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="JOBDATAITEMNAME" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SBRM_QTIME_DEF" Member="SBRM_QTIME_DEF">
    <Type Name="SBRM_QTIME_DEF">
      <Column Name="OBJECTKEY" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LINEID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SERVERNAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="QTIMEID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="STARTNODEID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="STARTNODENO" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="STARTNUNITID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="STARTNUNITNO" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="STARTEVENTMSG" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ENDNODEID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ENDNODENO" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ENDNUNITID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ENDNUNITNO" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ENDEVENTMSG" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SETTIMEVALUE" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="REMARK" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="STARTNODERECIPEID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SETCFRWVALUE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ENABLED" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.SBRM_RECIPEPARAMETER" Member="SBRM_RECIPEPARAMETER">
    <Type Name="SBRM_RECIPEPARAMETER">
      <Column Name="OBJECTKEY" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LINETYPE" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LINEID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SERVERNAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NODENO" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SVID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PARAMETERNAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ITEM" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SITE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DESCRIPTION" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="RANGE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="OPERATOR" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DOTRATIO" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="REPORTTO" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="REPORTUNITNO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UNIT" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EXPRESSION" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="WOFFSET" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="WPOINTS" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="BOFFSET" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="BPOINTS" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="JOBDATAITEMNAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SBRM_SKIPREPORT" Member="SBRM_SKIPREPORT">
    <Type Name="SBRM_SKIPREPORT">
      <Column Name="OBJECTKEY" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LINEID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NODEID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NODENO" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UNITNO" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UNITID" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="SKIPREPORTTRX" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SKIPAGENT" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SKIPCONDITION" Type="System.String" DbType="VarChar(512) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.SBRM_SUBJOBDATA" Member="SBRM_SUBJOBDATA">
    <Type Name="SBRM_SUBJOBDATA">
      <Column Name="OBJECTKEY" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LINETYPE" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ITEMNAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ITEMLENGTH" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SUBITEMNAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SUBITEMDESC" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="SUBITEMLOFFSET" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SUBITEMLENGTH" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MEMO" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SBRM_TACTTIME" Member="SBRM_TACTTIME">
    <Type Name="SBRM_TACTTIME">
      <Column Name="OBJECTKEY" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="LINEID" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="NODENO" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="UNITNO" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="TACKNO" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TACKNAME" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="POSITIONNO" Type="System.Double" DbType="Float" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SRCS_METHOD_DEF" Member="SRCS_METHOD_DEF">
    <Type Name="SRCS_METHOD_DEF">
      <Column Name="OBJECTKEY" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="METHODNAME" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="METHODTYPE" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="DESCRIPTION" Type="System.String" DbType="VarChar(1000) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.SBRM_UNIT" Member="SBRM_UNIT">
    <Type Name="SBRM_UNIT">
      <Column Name="OBJECTKEY" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="LINEID" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="NODEID" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="UNITNO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UNITID" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="NODENO" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="UNITTYPE" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="SERVERNAME" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ATTRIBUTE" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="USERUNMODE" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="SUBUNIT" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SBRM_ALARM" Member="SBRM_ALARM">
    <Type Name="SBRM_ALARM">
      <Column Name="OBJECTKEY" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="LINEID" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="NODENO" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="UNITNO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ALARMLEVEL" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ALARMID" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="BCALARMID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ALARMCODE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ALARMTEXT" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="SERVERNAME" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ALARMTYPECODE" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SBRM_RECIPE" Member="SBRM_RECIPE">
    <Type Name="SBRM_RECIPE">
      <Column Name="OBJECTKEY" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FABTYPE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LINETYPE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LINEID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NODENO" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="RECIPENO" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="RECIPEID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="RECIPENAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CREATETIME" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="VERSIONNO" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="RECIPESTATUS" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FILENAME" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="OPERATORID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>